[package]
name = "number_to_words"
version = "0.1.0"
authors = ["neverRare <35887047+neverRare@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
